[package]
name = "allocator"
version = "0.1.0"
edition = "2024"

[dependencies]
buddy_system_allocator = { version = "0.11.0", optional = true }

[features]
default = ["dep:buddy_system_allocator"]
    #   uses the default allocator
