[package]
name = "proc_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.28"
quote = "1.0.9"
syn = { version = "2.0.4", features = ["full", "visit-mut"] }

[lib]
proc-macro = true